import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { JotaiWrapper } from "@/wrappers/jotaiWrapper";
import { ThemeWrapper } from "@/wrappers/themeWrapper";
import { Navbar } from "@/components/navbar/navbar";
import { Box } from "@mui/material";
import DialogBox from "@/components/global/dialogBox";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <JotaiWrapper>
          <ThemeWrapper>
            <Navbar />
            <Box sx={{ padding: "10px" }}>{children}</Box>
            <DialogBox />
          </ThemeWrapper>
        </JotaiWrapper>
      </body>
    </html>
  );
}
